import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { getGuestLocation } from "@/redux/userSlice";
import { useDispatch } from "react-redux";

import { getCategories } from "@/redux/categoriesSlice";
import { store } from "../redux/store";

// import styles from "@/styles/Home.module.css";

export default function Home({ data }) {
  const dispatch = useDispatch();
  const [latitude, setLatitude] = useState(null);
  const [longitude, setLongitude] = useState(null);

  dispatch(getCategories(data));

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setLatitude(position.coords.latitude);
          setLongitude(position.coords.longitude);
        },
        (error) => {
          console.error(error);
        }
      );
    } else {
      console.error("Geolocation is not supported by this browser.");
    }
  }, []);

  useEffect(() => {
    const url = `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en
    `;

    fetch(url)
      .then((response) => response.json())
      .then((data) => {
        console.log(data.countryName);
        dispatch(getGuestLocation(data.countryName));
      })
      .catch((error) => console.error(error));
  }, [latitude, longitude]);

  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favIcon.png" />
      </Head>
      <main></main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("https://dummyjson.com/products/categories");
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
